### ISSUE TITLE
[추가]WIki 알고리즘 설명자료 - 한국어/알고리즘 목록 추가 

### ISSUE THREAD

**Issue by L2dulgi** [19-2-SKKU-OSS/2019-2-OSS-L6#18]
WIki 알고리즘 설명자료 - 한국어탭에서 이 프로젝트에서 구현된 알고리즘을 종류별로 한 눈에 볼 수 있도록 표를 새로 작성하고, 각 항목에 코드로 바로연결되는 링크를 추가하였습다.

**Comment by bidulki** [comment]
Math, Misc, datastructure 부분 안 된 것은 제가 할께요

**Comment by bidulki** [comment]
일단 data structure 부분은 추가했습니다

**Comment by bidulki** [comment]
나머지 부분도 추가했습니다
